baseURL = "https://SimY4.github.io"
title = "My personal space"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "actinglikecrazy"

[pagination]
pagerSize = 20

[params]
    author = "Alex Simkin"
    info = "Software Engineer, Geek"
    description = "Alex Simkin's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    since = 2019

    colorScheme = "auto"
    hidecolorschemetoggle = false

    customCSS = []

[taxonomies]
    category = "categories"
    tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/SimY4/"
[[params.social]]
    name = "StackOverflow"
    icon = "fa-brands fa-stack-overflow fa-2x fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/1439771/simy4/"
[[params.social]]
    name = "Instragram"
    icon = "fa-brands fa-instagram fa-2x"
    weight = 3
    url = "https://www.instagram.com/actinglikecrazy/"
[[params.social]]
    name = "Mastodon"
    icon = "fa-brands fa-mastodon fa-2x"
    weight = 4
    url = "https://aus.social/@actinglikecrazy/"
    rel = "me"
[[params.social]]
    name = "Bluesky"
    icon = "fa-brands fa-bluesky fa-2x"
    weight = 5
    url = "https://bsky.app/profile/simy4.github.io/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 6
    url = "https://www.linkedin.com/in/SimY4/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"
[[menu.main]]
    name = "RSS"
    weight = 3
    url = "/index.xml"
